unbind C-b
set-option -g prefix C-a
bind-key C-r source-file ~/.config/tmux/tmux.conf

set -g status-style bg=colour0

set-option -g set-clipboard on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
